// Code generated by echo. DO NOT EDIT.
// source: imdb.go

package imdb

import (
	"x.io/xrpc/pkg/echo"
)

func RegisterImdbServer(prefix string, e *echo.Echo, srv Imdb) error {
	var _ImdbServiceDesc = echo.ServiceDesc{
		ServiceName: "imdb.Imdb",
		HandlerType: (Imdb)(nil),
		Methods: []echo.MethodDesc{
			{
				MethodName: "FindFilm",
				HttpMethod: echo.GET,
				Path:       "/findfilm/:name",
				Handler:    srv.(Imdb).FindFilm,
			},
			{
				MethodName: "FindFilmPrice",
				HttpMethod: echo.GET,
				Path:       "/findfilm/:name/price",
				Handler:    srv.(Imdb).FindFilmPrice,
			},
			{
				MethodName: "FilmPriceUnit",
				HttpMethod: echo.GET,
				Path:       "/findfilm/:name/price/:unit",
				Handler:    srv.(Imdb).FilmPriceUnit,
			},
		},
		Metadata: "imdb",
	}
	if len(prefix) > 0 {
		var m *echo.MethodDesc
		for i := range _ImdbServiceDesc.Methods {
			m = &_ImdbServiceDesc.Methods[i]
			m.Path = prefix + m.Path
		}
	}
	return e.RegisterService(&_ImdbServiceDesc, srv)
}
